ALTER TABLE "Purchase" ADD COLUMN "paymentAmounts" DOUBLE PRECISION[] NOT NULL DEFAULT ARRAY[]::DOUBLE PRECISION[];
ALTER TABLE "SaleRecord" ADD COLUMN "paymentAmounts" DOUBLE PRECISION[] NOT NULL DEFAULT ARRAY[]::DOUBLE PRECISION[];
